steps:
- name: golang:1.21
  entrypoint: /bin/bash
  args:
  - -c
  - apt update && apt install -y zip && cd gcfnotifier && bash package.sh ${REVISION_ID}
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-crawler-cloud-function-sources/gcfnotifier'
    paths: ['gcfnotifier/${REVISION_ID}.zip']