version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/crawler/crawler"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/crawler/notifier"
    schedule:
      interval: "daily"