steps:
- name: golang:1.21
  entrypoint: /bin/bash
  args:
  - -c
  - apt update && apt install -y zip && cp package.sh ${FUNC_DIR} && cd ${FUNC_DIR} && bash package.sh ${REVISION_ID}
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-cloud-function-sources/${FUNC_DIR}'
    paths: ['${FUNC_DIR}/${REVISION_ID}.zip']