steps:
- name: golang:1.21
  entrypoint: /bin/bash
  args:
  - -c
  - apt update && apt install -y zip && bash package.sh ${TAG_NAME}
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-cloud-function-sources'
    paths: ['${TAG_NAME}.zip']