steps:
- name: golang:1.21
  entrypoint: /bin/bash
  args:
  - -c
  - apt update && apt install -y zip && cp package.sh ${_FUNC_DIR} && cd ${_FUNC_DIR} && bash package.sh ${TAG_NAME}
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-cloud-function-sources/${_FUNC_DIR}'
    paths: ['${_FUNC_DIR}/${TAG_NAME}.zip']