on:
  workflow_dispatch:

jobs:
  create-prerelease:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash create-prerelease.sh ${{ github.ref }}
        env:
          GH_TOKEN: ${{ github.token }}