on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.title, '[no release]')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash release.sh
        env:
          GH_TOKEN: ${{ github.token }}
