on:
  repository_dispatch:
    types: [create_pr_to_update_dependants_go_package]

jobs:
  create-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd crawler && go get -u ${{ github.event.client_payload.package }}@${{ github.event.client_payload.version }}
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git checkout -b up_go_depends/${{ github.event.client_payload.package }}-${{ github.event.client_payload.version }} origin/main
      - run: git commit -m "Automatically update dependants of go package\nUpdate version of ${{ github.event.client_payload.package }}@${{ github.event.client_payload.version }}" -a
      - run: git push origin `git rev-parse --abbrev-ref HEAD`
      - run: gh pr create --title "Up ${{ github.event.client_payload.package }} into ${{ github.event.client_payload.version }}" --body "${{ github.event.client_payload.package }}@${{ github.event.client_payload.version }}" --base main --head=up_go_depends/${{ github.event.client_payload.package }}-${{ github.event.client_payload.version }}
        env:
          GH_TOKEN: ${{ github.token }}
