on:
  repository_dispatch:
    types: [create_pr_to_update_dependants_go_package]

jobs:
  create-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.event.client_payload.version }}
      - run: echo ${{ github.event.client_payload.package }}
      - run: cd crawler/crawler && go get -u ${{ github.event.client_payload.package }}@${{ github.event.client_payload.version }}
      - run: cd crawler/notifier && go get -u ${{ github.event.client_payload.package }}@${{ github.event.client_payload.version }}
      - run: git diff